name: safenest
description: SafeNest - Maternal Safety Wearable Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # BLE
  flutter_blue_plus: ^1.32.12

  # Background service (keeps BLE alive when app closed)
  flutter_foreground_task: ^8.0.0

  # State management
  flutter_riverpod: ^2.5.1

  # Notifications
  flutter_local_notifications: ^17.2.2

  # Local storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # Utilities
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  app_settings: ^5.1.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  file_picker: ^10.3.10
  google_sign_in: ^6.2.1
  crypto: ^3.0.3
  local_auth: ^2.3.0
  image_picker: ^1.1.2
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login_illustration.png # ADDED FROM: C:\SafeNest app ui\Safenest blush ui\login page
    - assets/ui/create_account/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/safenest_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/safenest_icon.png"
